trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'DPDemo'
      repository: 'adodemo.azurecr.io'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildId)'
 